#region Using Directives

using System;
using System.Web.Services.Protocols;

#endregion

namespace Loom.Web.Services
{
    /// <summary>
    ///     ValidationAttribute triggers schema/assert validation through
    ///     the ValidationExtension class. For use on web methods
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class ValidationAttribute : SoapExtensionAttribute
    {
        /// <summary>
        ///     When true specifies that message received by web service
        ///     or generated by client for associated
        ///     web method should be checked against any associated Assert's
        /// </summary>
        private bool checkAssertions = true;

        /// <summary>
        ///     When true specifies that message received by web service
        ///     or generated by client for associated
        ///     web method should be validated against schema
        /// </summary>
        private bool schemaValidation = true;

        public ValidationAttribute()
        {
            Priority = 0;
        }

        /// <summary>
        ///     used to access the schemaValidation member
        /// </summary>
        public bool SchemaValidation
        {
            get => schemaValidation;
            set => schemaValidation = value;
        }

        /// <summary>
        ///     used to access the checkAssertions member
        /// </summary>
        public bool CheckAssertions
        {
            get => checkAssertions;
            set => checkAssertions = value;
        }

        /// <summary>
        ///     used by soap extension to get the type
        ///     of object to be created and initialized
        ///     for later processing of a web method
        /// </summary>
        public override Type ExtensionType => typeof(ValidationExtension);

        /// <summary>
        ///     used to access the priority member
        /// </summary>
        public override int Priority { get; set; }
    }
}