#region Using Directives

using System.Web;
using System.Xml;
using System.Xml.Schema;
using System.Xml.XPath;

#endregion

namespace Loom.Web.Services
{
    /// <summary>
    ///     intializer object generated by GetInitializer, stored by the
    ///     infrastructure, and provided to each call to Initialize
    ///     holds state used to perform schema/assertion validation
    /// </summary>
    internal class ValidationContext
    {
        /// <summary>
        ///     Used to hold all the Assert attributes for a web
        ///     method. These are used to build XPath expressions
        ///     to check the message.
        /// </summary>
        internal AssertAttribute[] AssertAttributes;

        /// <summary>
        ///     Used to keep track of whether this validation
        ///     context is for the class or particular method.
        ///     true means that the context is for a SoapAttribute
        ///     applied to the class
        /// </summary>
        internal bool ClassContext;

        /// <summary>
        ///     Used to hold XPath expression that AND's together
        ///     all of the XPath expressions contained the
        ///     AssertAttrute's associated with the web method
        /// </summary>
        internal XPathExpression CompleteRuleExpression;

        /// <summary>
        ///     hold endpoint being processeded.
        /// </summary>
        internal Endpoint CurrentEndpoint;

        /// <summary>
        ///     Used to hold namespaces that will be used
        ///     when checking Assert XPath expressions
        /// </summary>
        internal XmlNamespaceManager NamespaceManager;

        /// <summary>
        ///     Holds schemas used to validate messages.
        /// </summary>
        internal XmlSchemaSet SchemaCollection;

        /// <summary>
        ///     used to hold ValidationAttribute being processed
        ///     during initilization phase of processing a SOAP
        ///     extension
        /// </summary>
        internal ValidationAttribute ValidationAttribute;

        /// <summary>
        ///     Constructs a validation context.
        ///     It checks to see if there is an
        ///     HttpContext available set CurrentEndpoint
        ///     appropriately
        /// </summary>
        internal ValidationContext()
        {
            ClassContext = false;
            NamespaceManager = null;
            AssertAttributes = null;
            CompleteRuleExpression = null;
            ValidationAttribute = null;
            SchemaCollection = null;
            if (HttpContext.Current == null)
                CurrentEndpoint = Endpoint.Client;
            else
                CurrentEndpoint = Endpoint.Server;
        }
    }
}