#region Using Directives

using System;

#endregion

namespace Loom.CodeGeneration
{
    internal static class Messages
    {
        public static string NoDatabaseDefined(string inputFileName, string configFile)
        {
            return
                @"/**********************************************************************************************************" + Environment.NewLine +
                @"* ERROR: No connection string specified in configuration file." + Environment.NewLine +
                @"*        Configuration file located at " + configFile + Environment.NewLine +
                @"*        does not contain a connection string" + Environment.NewLine +
                @"* FILE: " + inputFileName + Environment.NewLine +
                @"***********************************************************************************************************/";
        }

        public static string ConfigFileNotSpecified(string inputFileName)
        {
            return
                @"/**********************************************************************************************************" + Environment.NewLine +
                @"* ERROR: Configuration file was not specified." + Environment.NewLine +
                @"* FILE: " + inputFileName + Environment.NewLine +
                @"* USAGE: #! config_file = PATH" + Environment.NewLine +
                @"***********************************************************************************************************/";
        }

        public static string ConfigFileNotFound(string inputFileName, string configFile)
        {
            return
                @"/**********************************************************************************************************" + Environment.NewLine +
                @"* ERROR: Configuration file was not found." + Environment.NewLine +
                @"*        Path specified in file " + inputFileName + " was not found" + Environment.NewLine +
                @"* PATH: " + configFile + Environment.NewLine +
                @"* USAGE: #! config_file = PATH" + Environment.NewLine +
                @"***********************************************************************************************************/";
        }

        public static string FileHeader(string inputFileName)
        {
            return
                @"// -----------------------------------------------------------------------------" + Environment.NewLine +
                @"//  <autogeneratedinfo>" + Environment.NewLine +
                @"//      This code was generated by:" + Environment.NewLine +
                @"//        ActiveMap Generator custom tool for VS.NET 2005, by Brian Scott" + Environment.NewLine +
                @"// " + Environment.NewLine +
                @"//      It contains data access classes from the database defined in the file:" + Environment.NewLine +
                @"//        " + inputFileName + Environment.NewLine +
                @"// " + Environment.NewLine +
                @"//      Generated: " + DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString() + Environment.NewLine +
                @"//  </autogeneratedinfo>" + Environment.NewLine +
                @"// -----------------------------------------------------------------------------" + Environment.NewLine + Environment.NewLine;
        }
    }
}