//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Web.Configuration {
    using System;
    using System.Configuration;
    
    
    public class DefaultDocumentElement : System.Configuration.ConfigurationElement {
        
        [System.Configuration.ConfigurationProperty("path", DefaultValue="", IsKey=false, IsRequired=false)]
        public string Path {
            get {
                return ((string)(base["path"]));
            }
            set {
                base["path"] = value;
            }
        }
    }
    
    public class DocumentRedirectSettingsSection : System.Configuration.ConfigurationSection {
        
        [System.Configuration.ConfigurationProperty("defaultDocument")]
        public DefaultDocumentElement DefaultDocument {
            get {
                return ((DefaultDocumentElement)(base["defaultDocument"]));
            }
        }
    }
}
