//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Web.Configuration {
    using System;
    using System.Configuration;
    
    
    public class FileNotFoundElement : System.Configuration.ConfigurationElement {
        
        [System.Configuration.ConfigurationProperty("redirect", DefaultValue="", IsKey=false, IsRequired=false)]
        public string Redirect {
            get {
                return ((string)(base["redirect"]));
            }
            set {
                base["redirect"] = value;
            }
        }
        
        [System.Configuration.ConfigurationProperty("message", DefaultValue="", IsKey=false, IsRequired=false)]
        public string Message {
            get {
                return ((string)(base["message"]));
            }
            set {
                base["message"] = value;
            }
        }
    }
    
    public class MaliciousInputElement : System.Configuration.ConfigurationElement {
        
        [System.Configuration.ConfigurationProperty("redirect", DefaultValue="", IsKey=false, IsRequired=false)]
        public string Redirect {
            get {
                return ((string)(base["redirect"]));
            }
            set {
                base["redirect"] = value;
            }
        }
        
        [System.Configuration.ConfigurationProperty("message", DefaultValue="", IsKey=false, IsRequired=false)]
        public string Message {
            get {
                return ((string)(base["message"]));
            }
            set {
                base["message"] = value;
            }
        }
    }
    
    public class ErrorHandlingSettingsSection : System.Configuration.ConfigurationSection {
        
        [System.Configuration.ConfigurationProperty("defaultRedirect", DefaultValue="", IsKey=false, IsRequired=false)]
        public string DefaultRedirect {
            get {
                return ((string)(base["defaultRedirect"]));
            }
            set {
                base["defaultRedirect"] = value;
            }
        }
        
        [System.Configuration.ConfigurationProperty("defaultMessage", DefaultValue="", IsKey=false, IsRequired=false)]
        public string DefaultMessage {
            get {
                return ((string)(base["defaultMessage"]));
            }
            set {
                base["defaultMessage"] = value;
            }
        }
        
        [System.Configuration.ConfigurationProperty("fileNotFound")]
        public FileNotFoundElement FileNotFound {
            get {
                return ((FileNotFoundElement)(base["fileNotFound"]));
            }
        }
        
        [System.Configuration.ConfigurationProperty("maliciousInput")]
        public MaliciousInputElement MaliciousInput {
            get {
                return ((MaliciousInputElement)(base["maliciousInput"]));
            }
        }
    }
}
