//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Web.Portal.WebTest {
    
    
    public partial class PortalControls {
        
        /// <summary>
        /// downloader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.FileDownload downloader;
        
        /// <summary>
        /// bindTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.ListBox bindTest;
        
        /// <summary>
        /// select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.ListBox select;
        
        /// <summary>
        /// enumList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.DropDownList enumList;
        
        /// <summary>
        /// checkbox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.CheckBox checkbox;
        
        /// <summary>
        /// radiobutton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.RadioButton radiobutton;
        
        /// <summary>
        /// dfjgvfdsfsddjfd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.TextBox dfjgvfdsfsddjfd;
        
        /// <summary>
        /// adas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.StyleSheet adas;
        
        /// <summary>
        /// javaScriptTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.Script javaScriptTest;
        
        /// <summary>
        /// Case0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.Case Case0;
        
        /// <summary>
        /// Case1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.Case Case1;
        
        /// <summary>
        /// Case2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.Case Case2;
        
        /// <summary>
        /// propertyGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.PropertyGrid propertyGrid;
        
        /// <summary>
        /// propertyValues control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.Portal.UI.Controls.Label propertyValues;
    }
}
