//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.20506.1.
// 
#pragma warning disable 1591

namespace Colossus.Framework.Windows.Forms.Tests.ActiveData {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActiveMapTestsSoap", Namespace="http://www.devinterop.com/framework/data/active/tests")]
    public partial class ActiveMapTests : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSalesReasonValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShipMethodValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesReasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShipMethodOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesOrderHeaderSalesReasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompositeObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateProductOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActiveMapTests() {
            this.Url = global::Colossus.Framework.Windows.Forms.Tests.Properties.Settings.Default.DevInterop_Framework_Windows_Forms_Tests_ActiveData_ActiveMapTests;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSalesReasonValuesCompletedEventHandler GetSalesReasonValuesCompleted;
        
        /// <remarks/>
        public event GetShipMethodValuesCompletedEventHandler GetShipMethodValuesCompleted;
        
        /// <remarks/>
        public event GetSalesReasonCompletedEventHandler GetSalesReasonCompleted;
        
        /// <remarks/>
        public event GetShipMethodCompletedEventHandler GetShipMethodCompleted;
        
        /// <remarks/>
        public event GetSalesOrderHeaderSalesReasonCompletedEventHandler GetSalesOrderHeaderSalesReasonCompleted;
        
        /// <remarks/>
        public event GetCompositeObjectCompletedEventHandler GetCompositeObjectCompleted;
        
        /// <remarks/>
        public event GetProductCompletedEventHandler GetProductCompleted;
        
        /// <remarks/>
        public event CreateProductCompletedEventHandler CreateProductCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetSalesReasonValues", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetSalesReasonValues() {
            object[] results = this.Invoke("GetSalesReasonValues", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesReasonValuesAsync() {
            this.GetSalesReasonValuesAsync(null);
        }
        
        /// <remarks/>
        public void GetSalesReasonValuesAsync(object userState) {
            if ((this.GetSalesReasonValuesOperationCompleted == null)) {
                this.GetSalesReasonValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesReasonValuesOperationCompleted);
            }
            this.InvokeAsync("GetSalesReasonValues", new object[0], this.GetSalesReasonValuesOperationCompleted, userState);
        }
        
        private void OnGetSalesReasonValuesOperationCompleted(object arg) {
            if ((this.GetSalesReasonValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesReasonValuesCompleted(this, new GetSalesReasonValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetShipMethodValues", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetShipMethodValues() {
            object[] results = this.Invoke("GetShipMethodValues", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShipMethodValuesAsync() {
            this.GetShipMethodValuesAsync(null);
        }
        
        /// <remarks/>
        public void GetShipMethodValuesAsync(object userState) {
            if ((this.GetShipMethodValuesOperationCompleted == null)) {
                this.GetShipMethodValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShipMethodValuesOperationCompleted);
            }
            this.InvokeAsync("GetShipMethodValues", new object[0], this.GetShipMethodValuesOperationCompleted, userState);
        }
        
        private void OnGetShipMethodValuesOperationCompleted(object arg) {
            if ((this.GetShipMethodValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShipMethodValuesCompleted(this, new GetShipMethodValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetSalesReason", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LookupListEntryOfInt32String[] GetSalesReason() {
            object[] results = this.Invoke("GetSalesReason", new object[0]);
            return ((LookupListEntryOfInt32String[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesReasonAsync() {
            this.GetSalesReasonAsync(null);
        }
        
        /// <remarks/>
        public void GetSalesReasonAsync(object userState) {
            if ((this.GetSalesReasonOperationCompleted == null)) {
                this.GetSalesReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesReasonOperationCompleted);
            }
            this.InvokeAsync("GetSalesReason", new object[0], this.GetSalesReasonOperationCompleted, userState);
        }
        
        private void OnGetSalesReasonOperationCompleted(object arg) {
            if ((this.GetSalesReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesReasonCompleted(this, new GetSalesReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetShipMethod", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LookupListEntryOfInt32String[] GetShipMethod() {
            object[] results = this.Invoke("GetShipMethod", new object[0]);
            return ((LookupListEntryOfInt32String[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShipMethodAsync() {
            this.GetShipMethodAsync(null);
        }
        
        /// <remarks/>
        public void GetShipMethodAsync(object userState) {
            if ((this.GetShipMethodOperationCompleted == null)) {
                this.GetShipMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShipMethodOperationCompleted);
            }
            this.InvokeAsync("GetShipMethod", new object[0], this.GetShipMethodOperationCompleted, userState);
        }
        
        private void OnGetShipMethodOperationCompleted(object arg) {
            if ((this.GetShipMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShipMethodCompleted(this, new GetShipMethodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetSalesOrderHeaderSalesRea" +
            "son", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LookupListEntryOfInt32Int32[] GetSalesOrderHeaderSalesReason() {
            object[] results = this.Invoke("GetSalesOrderHeaderSalesReason", new object[0]);
            return ((LookupListEntryOfInt32Int32[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesOrderHeaderSalesReasonAsync() {
            this.GetSalesOrderHeaderSalesReasonAsync(null);
        }
        
        /// <remarks/>
        public void GetSalesOrderHeaderSalesReasonAsync(object userState) {
            if ((this.GetSalesOrderHeaderSalesReasonOperationCompleted == null)) {
                this.GetSalesOrderHeaderSalesReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesOrderHeaderSalesReasonOperationCompleted);
            }
            this.InvokeAsync("GetSalesOrderHeaderSalesReason", new object[0], this.GetSalesOrderHeaderSalesReasonOperationCompleted, userState);
        }
        
        private void OnGetSalesOrderHeaderSalesReasonOperationCompleted(object arg) {
            if ((this.GetSalesOrderHeaderSalesReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesOrderHeaderSalesReasonCompleted(this, new GetSalesOrderHeaderSalesReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetCompositeObject", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TestClass GetCompositeObject() {
            object[] results = this.Invoke("GetCompositeObject", new object[0]);
            return ((TestClass)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompositeObjectAsync() {
            this.GetCompositeObjectAsync(null);
        }
        
        /// <remarks/>
        public void GetCompositeObjectAsync(object userState) {
            if ((this.GetCompositeObjectOperationCompleted == null)) {
                this.GetCompositeObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompositeObjectOperationCompleted);
            }
            this.InvokeAsync("GetCompositeObject", new object[0], this.GetCompositeObjectOperationCompleted, userState);
        }
        
        private void OnGetCompositeObjectOperationCompleted(object arg) {
            if ((this.GetCompositeObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompositeObjectCompleted(this, new GetCompositeObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetProduct", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product GetProduct() {
            object[] results = this.Invoke("GetProduct", new object[0]);
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductAsync() {
            this.GetProductAsync(null);
        }
        
        /// <remarks/>
        public void GetProductAsync(object userState) {
            if ((this.GetProductOperationCompleted == null)) {
                this.GetProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductOperationCompleted);
            }
            this.InvokeAsync("GetProduct", new object[0], this.GetProductOperationCompleted, userState);
        }
        
        private void OnGetProductOperationCompleted(object arg) {
            if ((this.GetProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductCompleted(this, new GetProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/CreateProduct", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product CreateProduct() {
            object[] results = this.Invoke("CreateProduct", new object[0]);
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProductAsync() {
            this.CreateProductAsync(null);
        }
        
        /// <remarks/>
        public void CreateProductAsync(object userState) {
            if ((this.CreateProductOperationCompleted == null)) {
                this.CreateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProductOperationCompleted);
            }
            this.InvokeAsync("CreateProduct", new object[0], this.CreateProductOperationCompleted, userState);
        }
        
        private void OnCreateProductOperationCompleted(object arg) {
            if ((this.CreateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProductCompleted(this, new CreateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devinterop.com/framework/data/active/tests")]
    public partial class LookupListEntryOfInt32String {
        
        private int keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devinterop.com/framework/data/active")]
    public partial class Product {
        
        private int productIDField;
        
        private string nameField;
        
        private string productNumberField;
        
        private bool makeFlagField;
        
        private bool finishedGoodsFlagField;
        
        private string colorField;
        
        private short safetyStockLevelField;
        
        private short reorderPointField;
        
        private decimal standardCostField;
        
        private decimal listPriceField;
        
        private string sizeField;
        
        private string sizeUnitMeasureCodeField;
        
        private string weightUnitMeasureCodeField;
        
        private System.Nullable<decimal> weightField;
        
        private int daysToManufactureField;
        
        private string productLineField;
        
        private string classField;
        
        private string styleField;
        
        private System.Nullable<int> productSubcategoryIDField;
        
        private System.Nullable<int> productModelIDField;
        
        private System.DateTime sellStartDateField;
        
        private System.Nullable<System.DateTime> sellEndDateField;
        
        private System.Nullable<System.DateTime> discontinuedDateField;
        
        private string rowguidField;
        
        private System.DateTime modifiedDateField;
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool MakeFlag {
            get {
                return this.makeFlagField;
            }
            set {
                this.makeFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool FinishedGoodsFlag {
            get {
                return this.finishedGoodsFlagField;
            }
            set {
                this.finishedGoodsFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public short SafetyStockLevel {
            get {
                return this.safetyStockLevelField;
            }
            set {
                this.safetyStockLevelField = value;
            }
        }
        
        /// <remarks/>
        public short ReorderPoint {
            get {
                return this.reorderPointField;
            }
            set {
                this.reorderPointField = value;
            }
        }
        
        /// <remarks/>
        public decimal StandardCost {
            get {
                return this.standardCostField;
            }
            set {
                this.standardCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SizeUnitMeasureCode {
            get {
                return this.sizeUnitMeasureCodeField;
            }
            set {
                this.sizeUnitMeasureCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WeightUnitMeasureCode {
            get {
                return this.weightUnitMeasureCodeField;
            }
            set {
                this.weightUnitMeasureCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int DaysToManufacture {
            get {
                return this.daysToManufactureField;
            }
            set {
                this.daysToManufactureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductLine {
            get {
                return this.productLineField;
            }
            set {
                this.productLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductSubcategoryID {
            get {
                return this.productSubcategoryIDField;
            }
            set {
                this.productSubcategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductModelID {
            get {
                return this.productModelIDField;
            }
            set {
                this.productModelIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SellStartDate {
            get {
                return this.sellStartDateField;
            }
            set {
                this.sellStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SellEndDate {
            get {
                return this.sellEndDateField;
            }
            set {
                this.sellEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DiscontinuedDate {
            get {
                return this.discontinuedDateField;
            }
            set {
                this.discontinuedDateField = value;
            }
        }
        
        /// <remarks/>
        public string rowguid {
            get {
                return this.rowguidField;
            }
            set {
                this.rowguidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devinterop.com/framework/data/active/tests")]
    public partial class TestClass {
        
        private LookupListEntryOfInt32String[] reasonField;
        
        private LookupListEntryOfInt32String[] methodField;
        
        private string nameField;
        
        /// <remarks/>
        public LookupListEntryOfInt32String[] Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public LookupListEntryOfInt32String[] Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devinterop.com/framework/data/active/tests")]
    public partial class LookupListEntryOfInt32Int32 {
        
        private int keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetSalesReasonValuesCompletedEventHandler(object sender, GetSalesReasonValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesReasonValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesReasonValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetShipMethodValuesCompletedEventHandler(object sender, GetShipMethodValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShipMethodValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShipMethodValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetSalesReasonCompletedEventHandler(object sender, GetSalesReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LookupListEntryOfInt32String[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LookupListEntryOfInt32String[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetShipMethodCompletedEventHandler(object sender, GetShipMethodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShipMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShipMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LookupListEntryOfInt32String[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LookupListEntryOfInt32String[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetSalesOrderHeaderSalesReasonCompletedEventHandler(object sender, GetSalesOrderHeaderSalesReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesOrderHeaderSalesReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesOrderHeaderSalesReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LookupListEntryOfInt32Int32[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LookupListEntryOfInt32Int32[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetCompositeObjectCompletedEventHandler(object sender, GetCompositeObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompositeObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompositeObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestClass Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestClass)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetProductCompletedEventHandler(object sender, GetProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void CreateProductCompletedEventHandler(object sender, CreateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591