//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colossus.Framework.Web.Portal.Resources.Templates {


    public partial class Error
    {
        
        /// <summary>
        /// pageHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Colossus.Framework.Web.Portal.UI.Controls.Box pageHeader;
        
        /// <summary>
        /// menu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Colossus.Framework.Web.Portal.UI.Controls.Box menu;
        
        /// <summary>
        /// middlePart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Colossus.Framework.Web.Portal.UI.Controls.Box middlePart;
    }
}
