//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Web.Tests {
    
    
    public partial class Controls {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ButtonEx2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.ButtonEx ButtonEx2;
        
        /// <summary>
        /// ButtonEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.ButtonEx ButtonEx1;
        
        /// <summary>
        /// TextBoxEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.TextBoxEx TextBoxEx1;
        
        /// <summary>
        /// ImageEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.ImageEx ImageEx1;
        
        /// <summary>
        /// ImageEx2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.HyperLinkEx ImageEx2;
        
        /// <summary>
        /// RepeaterEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.RepeaterEx RepeaterEx1;
        
        /// <summary>
        /// cmsContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.CMS.CmsContainer cmsContainer;
        
        /// <summary>
        /// cmsEntityView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.CMS.CmsEntityView cmsEntityView1;
        
        /// <summary>
        /// entityView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.EntityView entityView1;
        
        /// <summary>
        /// TreeView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.TreeView TreeView1;
        
        /// <summary>
        /// BulletedListEx1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Loom.Web.UI.WebControls.BulletedListEx BulletedListEx1;
    }
}
