//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Data.Mapping {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loom.Data.Mapping.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     /// &lt;summary&gt;
        ///    /// This is an DataRecord class which wraps the #SCHEMA#.#TABLE# table.
        ///    /// &lt;/summary&gt;
        ///    [Serializable, XmlSchemaProvider(&quot;CreateSchema&quot;)]
        ///    [#SCHEMAATTRIBUTES#]
        ///    #ADDITIONALATTRIBUTES#public partial class #CLASSNAME# : DataRecord&lt;#CLASSNAME#&gt; 
        ///    {    
        ///        #region Column Names	
        ///        public struct Columns 
        ///        {
        ///#COLUMNLIST#
        ///        }
        ///        #endregion
        ///        
        ///        #region Member Fields
        ///#MEMBERFIELDS#
        ///        #endregion
        ///
        ///        public stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActiveRecordClass {
            get {
                return ResourceManager.GetString("ActiveRecordClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///
        ///using System;
        ///using System.Data.Common;
        ///using Loom.Data.Mapping;
        ///using Loom.Data.Mapping.Providers;
        ///#NAMESPACELIST#
        ///
        ///#endregion
        ///
        ///namespace #NAMESPACE#   
        ///{
        ///    public class #CLASSNAME# : DataSession, I#CLASSNAME#
        ///    {
        ///        public #CLASSNAME#() : base(&quot;#PROVIDERNAME#&quot;) {}
        ///        public #CLASSNAME#(string sessionProviderName) : base(sessionProviderName) {}
        ///        public #CLASSNAME#(IActiveDataProvider provider, string connectionString) : base(provider, connectio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataSessionClass {
            get {
                return ResourceManager.GetString("DataSessionClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         EntitySet&lt;#NAMESPACE#.#SCHEMA##TABLE#&gt; #PROPERTYNAME# { get; }.
        /// </summary>
        internal static string DataSessionInterfaceProperty {
            get {
                return ResourceManager.GetString("DataSessionInterfaceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         public EntitySet&lt;#NAMESPACE#.#SCHEMA##TABLE#&gt; #PROPERTYNAME#
        ///        {
        ///            get { return EntitySet&lt;#NAMESPACE#.#SCHEMA##TABLE#&gt;(); }
        ///        }.
        /// </summary>
        internal static string DataSessionProperty {
            get {
                return ResourceManager.GetString("DataSessionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     /// &lt;summary&gt;
        ///    /// This is an enum which wraps the #SCHEMA#.#TABLE# table.
        ///    /// &lt;/summary&gt;
        ///    public enum #CLASSNAME#
        ///    {
        ///#ENUMVALUES#
        ///    }.
        /// </summary>
        internal static string Enum {
            get {
                return ResourceManager.GetString("Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         /// &lt;summary&gt;
        ///        /// #SUMMARY#
        ///        /// &lt;/summary&gt;
        ///        [#SCHEMAATTRIBUTES#]
        ///#ADDITIONALATTRIBUTES#        public #ENUMTYPE# #PROPERTYNAME#
        ///        { 
        ///            get
        ///            {
        ///                return _#FIELDNAME#;
        ///            }
        ///            set
        ///            {
        ///                if(value == _#FIELDNAME#)
        ///                    return;
        ///                    
        ///                _#FIELDNAME# = value;
        ///                MarkDirty(&quot;#COLUMN#&quot;);
        ///            }
        ///        }.
        /// </summary>
        internal static string EnumProperty {
            get {
                return ResourceManager.GetString("EnumProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region Using Directives
        ///
        ///using System;
        ///using System.Data.Common;
        ///using Loom.Data.Mapping;
        ///using Loom.Data.Mapping.Providers;
        ///#NAMESPACELIST#
        ///
        ///#endregion
        ///
        ///namespace #NAMESPACE#
        ///{
        ///    public interface I#CLASSNAME#
        ///    {
        ///#PROPERTIES#
        ///    }
        ///}.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// This is an StoredProcedure class which wraps the #SCHEMA#.#PROCEDURENAME# procedure.
        ////// &lt;/summary&gt;
        ///[Serializable]
        ///[#SCHEMAATTRIBUTES#]
        ///public partial class #CLASSNAME# : StoredProcedure&lt;#CLASSNAME#&gt; {
        ///    #region Parameter Names    
        ///    public struct Parameters {
        ///#PARAMETERLIST#
        ///    }
        ///    #endregion
        ///    	
        ///    #region Column Property Accessors	
        ///#PROPERTIES#
        ///    #endregion
        ///}.
        /// </summary>
        internal static string ProcedureClass {
            get {
                return ResourceManager.GetString("ProcedureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [#SCHEMAATTRIBUTES#]
        ///    public #DATATYPESHORT# #PROPERTYNAME#{ get; set; }.
        /// </summary>
        internal static string ProcedureProperty {
            get {
                return ResourceManager.GetString("ProcedureProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         /// &lt;summary&gt;
        ///        /// #SUMMARY#
        ///        /// &lt;/summary&gt;
        ///        [#SCHEMAATTRIBUTES#]
        ///#ADDITIONALATTRIBUTES#        public #DATATYPESHORT# #PROPERTYNAME# 
        ///        { 
        ///            get
        ///            {
        ///                return _#FIELDNAME#;
        ///            }
        ///            set
        ///            {
        ///                if(value == _#FIELDNAME# &amp;&amp; IsPropertyDirty(&quot;#COLUMN#&quot;))
        ///                    return;
        ///                    
        ///                _#FIELDNAME# = value;
        ///                MarkDirty(&quot;#COLUMN#&quot;);
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
    }
}
