//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.20506.1.
// 
#pragma warning disable 1591

namespace Colossus.Framework.Web.Tests.AdventureWorksService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActiveMapTestsSoap", Namespace="http://www.devinterop.com/framework/data/active/tests")]
    public partial class ActiveMapTests : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductPhotosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCustomerBasicOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ActiveMapTests() {
            this.Url = global::Colossus.Framework.Web.Tests.Properties.Settings.Default.Framework_WebTests_AdventureWorksService_ActiveMapTests;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductCompletedEventHandler GetProductCompleted;
        
        /// <remarks/>
        public event GetProductPhotosCompletedEventHandler GetProductPhotosCompleted;
        
        /// <remarks/>
        public event CreateProductCompletedEventHandler CreateProductCompleted;
        
        /// <remarks/>
        public event CreateCustomerBasicCompletedEventHandler CreateCustomerBasicCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetProduct", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product GetProduct() {
            object[] results = this.Invoke("GetProduct", new object[0]);
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductAsync() {
            this.GetProductAsync(null);
        }
        
        /// <remarks/>
        public void GetProductAsync(object userState) {
            if ((this.GetProductOperationCompleted == null)) {
                this.GetProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductOperationCompleted);
            }
            this.InvokeAsync("GetProduct", new object[0], this.GetProductOperationCompleted, userState);
        }
        
        private void OnGetProductOperationCompleted(object arg) {
            if ((this.GetProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductCompleted(this, new GetProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/GetProductPhotos", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductPhoto GetProductPhotos() {
            object[] results = this.Invoke("GetProductPhotos", new object[0]);
            return ((ProductPhoto)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductPhotosAsync() {
            this.GetProductPhotosAsync(null);
        }
        
        /// <remarks/>
        public void GetProductPhotosAsync(object userState) {
            if ((this.GetProductPhotosOperationCompleted == null)) {
                this.GetProductPhotosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductPhotosOperationCompleted);
            }
            this.InvokeAsync("GetProductPhotos", new object[0], this.GetProductPhotosOperationCompleted, userState);
        }
        
        private void OnGetProductPhotosOperationCompleted(object arg) {
            if ((this.GetProductPhotosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductPhotosCompleted(this, new GetProductPhotosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/CreateProduct", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product CreateProduct() {
            object[] results = this.Invoke("CreateProduct", new object[0]);
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProductAsync() {
            this.CreateProductAsync(null);
        }
        
        /// <remarks/>
        public void CreateProductAsync(object userState) {
            if ((this.CreateProductOperationCompleted == null)) {
                this.CreateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProductOperationCompleted);
            }
            this.InvokeAsync("CreateProduct", new object[0], this.CreateProductOperationCompleted, userState);
        }
        
        private void OnCreateProductOperationCompleted(object arg) {
            if ((this.CreateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProductCompleted(this, new CreateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.devinterop.com/framework/data/active/tests/CreateCustomerBasic", RequestNamespace="http://www.devinterop.com/framework/data/active/tests", ResponseNamespace="http://www.devinterop.com/framework/data/active/tests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerBasic CreateCustomerBasic() {
            object[] results = this.Invoke("CreateCustomerBasic", new object[0]);
            return ((CustomerBasic)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCustomerBasicAsync() {
            this.CreateCustomerBasicAsync(null);
        }
        
        /// <remarks/>
        public void CreateCustomerBasicAsync(object userState) {
            if ((this.CreateCustomerBasicOperationCompleted == null)) {
                this.CreateCustomerBasicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCustomerBasicOperationCompleted);
            }
            this.InvokeAsync("CreateCustomerBasic", new object[0], this.CreateCustomerBasicOperationCompleted, userState);
        }
        
        private void OnCreateCustomerBasicOperationCompleted(object arg) {
            if ((this.CreateCustomerBasicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCustomerBasicCompleted(this, new CreateCustomerBasicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Product {
        
        private int productIDField;
        
        private string nameField;
        
        private string productNumberField;
        
        private bool makeFlagField;
        
        private bool finishedGoodsFlagField;
        
        private string colorField;
        
        private short safetyStockLevelField;
        
        private short reorderPointField;
        
        private decimal standardCostField;
        
        private decimal listPriceField;
        
        private string sizeField;
        
        private string sizeUnitMeasureCodeField;
        
        private string weightUnitMeasureCodeField;
        
        private System.Nullable<decimal> weightField;
        
        private int daysToManufactureField;
        
        private string productLineField;
        
        private string classField;
        
        private string styleField;
        
        private System.Nullable<int> productSubcategoryIDField;
        
        private System.Nullable<int> productModelIDField;
        
        private System.DateTime sellStartDateField;
        
        private System.Nullable<System.DateTime> sellEndDateField;
        
        private System.Nullable<System.DateTime> discontinuedDateField;
        
        private string rowguidField;
        
        private System.DateTime modifiedDateField;
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool MakeFlag {
            get {
                return this.makeFlagField;
            }
            set {
                this.makeFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool FinishedGoodsFlag {
            get {
                return this.finishedGoodsFlagField;
            }
            set {
                this.finishedGoodsFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public short SafetyStockLevel {
            get {
                return this.safetyStockLevelField;
            }
            set {
                this.safetyStockLevelField = value;
            }
        }
        
        /// <remarks/>
        public short ReorderPoint {
            get {
                return this.reorderPointField;
            }
            set {
                this.reorderPointField = value;
            }
        }
        
        /// <remarks/>
        public decimal StandardCost {
            get {
                return this.standardCostField;
            }
            set {
                this.standardCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal ListPrice {
            get {
                return this.listPriceField;
            }
            set {
                this.listPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SizeUnitMeasureCode {
            get {
                return this.sizeUnitMeasureCodeField;
            }
            set {
                this.sizeUnitMeasureCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WeightUnitMeasureCode {
            get {
                return this.weightUnitMeasureCodeField;
            }
            set {
                this.weightUnitMeasureCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int DaysToManufacture {
            get {
                return this.daysToManufactureField;
            }
            set {
                this.daysToManufactureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductLine {
            get {
                return this.productLineField;
            }
            set {
                this.productLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductSubcategoryID {
            get {
                return this.productSubcategoryIDField;
            }
            set {
                this.productSubcategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductModelID {
            get {
                return this.productModelIDField;
            }
            set {
                this.productModelIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SellStartDate {
            get {
                return this.sellStartDateField;
            }
            set {
                this.sellStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SellEndDate {
            get {
                return this.sellEndDateField;
            }
            set {
                this.sellEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DiscontinuedDate {
            get {
                return this.discontinuedDateField;
            }
            set {
                this.discontinuedDateField = value;
            }
        }
        
        /// <remarks/>
        public string rowguid {
            get {
                return this.rowguidField;
            }
            set {
                this.rowguidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.devinterop.com/framework/data/active/tests")]
    public partial class CustomerBasic {
        
        private int customerIdField;
        
        private string nameField;
        
        /// <remarks/>
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.20506.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductPhoto {
        
        private int productPhotoIDField;
        
        private string thumbNailPhotoField;
        
        private string thumbnailPhotoFileNameField;
        
        private string largePhotoField;
        
        private string largePhotoFileNameField;
        
        private System.DateTime modifiedDateField;
        
        /// <remarks/>
        public int ProductPhotoID {
            get {
                return this.productPhotoIDField;
            }
            set {
                this.productPhotoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ThumbNailPhoto {
            get {
                return this.thumbNailPhotoField;
            }
            set {
                this.thumbNailPhotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ThumbnailPhotoFileName {
            get {
                return this.thumbnailPhotoFileNameField;
            }
            set {
                this.thumbnailPhotoFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LargePhoto {
            get {
                return this.largePhotoField;
            }
            set {
                this.largePhotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LargePhotoFileName {
            get {
                return this.largePhotoFileNameField;
            }
            set {
                this.largePhotoFileNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetProductCompletedEventHandler(object sender, GetProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void GetProductPhotosCompletedEventHandler(object sender, GetProductPhotosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductPhotosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductPhotosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductPhoto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductPhoto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void CreateProductCompletedEventHandler(object sender, CreateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void CreateCustomerBasicCompletedEventHandler(object sender, CreateCustomerBasicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCustomerBasicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCustomerBasicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerBasic Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerBasic)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591