#region Using Directives

using System.Diagnostics.CodeAnalysis;

#endregion

[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Loom.Collections.Generic")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Loom.Cryptography")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Loom.IO.Compression")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.ThreadStart")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.TimerCallback")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.WaitCallback")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Loom.GenericPool{T}.RetrieveObjectFromPool():T")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Loom.IO")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Loom.Cryptography.SymmetricCryptographyProvider.System.IDisposable.Dispose():System.Void")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Loom.Security.Adler32.Update(System.Byte[],System.Int32,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.Security.Crc32..ctor()")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Loom.Security.Crc32.Update(System.Byte[],System.Int32,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", Scope = "member", Target = "Loom.IO.Compression.Zip.Deflater.Deflate(System.Byte[],System.Int32,System.Int32):System.Int32", MessageId = "System.InvalidOperationException.#ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", Scope = "member", Target = "Loom.IO.Compression.Zip.Deflater.SetInput(System.Byte[],System.Int32,System.Int32):System.Void", MessageId = "System.InvalidOperationException.#ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.IO.Compression.Zip.Deflater..cctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Loom.IO.Compression.Zip.DeflaterHuffman..cctor()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Scope = "member", Target = "Loom.IO.Compression.Zip.DeflaterOutputStream..ctor(System.IO.Stream,Loom.IO.Compression.Zip.Deflater,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", Scope = "member", Target = "Loom.IO.Compression.Zip.DeflaterOutputStream..ctor(System.IO.Stream,Loom.IO.Compression.Zip.Deflater,System.Int32)", MessageId = "System.ArgumentException.#ctor(System.String,System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.IO.Compression.Zip.DeflaterOutputStream..ctor(System.IO.Stream,Loom.IO.Compression.Zip.Deflater,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Loom.IO.Compression.Zip.DeflaterOutputStream..ctor(System.IO.Stream,Loom.IO.Compression.Zip.Deflater,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.IO.Compression.Zip.ZipConstants..cctor()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", Scope = "member", Target = "Loom.IO.Compression.Zip.ZipEntry..ctor(System.String,System.Int32,System.Int32)", MessageId = "System.ArgumentException.#ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.IO.Compression.Zip.ZipEntry..ctor(System.String,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.IO.Compression.Zip.ZipEntry..ctor(Loom.IO.Compression.Zip.ZipEntry)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Loom.IO.Compression.Zip.ZipEntry..ctor(System.String,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope = "member", Target = "Loom.IO.Compression.Zip.ZipOutputStream..ctor(System.IO.Stream)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "member", Target = "Loom.Cryptography.SymmetricCryptographyProvider.System.IDisposable.Dispose():System.Void")]
[assembly: SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "member", Target = "Loom.Cryptography.HashProvider.System.IDisposable.Dispose():System.Void")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Loom.Collections.Generic.Tree{T}+BranchCollection.Add(System.Collections.Generic.IEnumerable{T}<Loom.Collections.Generic.Tree{T}<T>>):System.Void")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Loom.Collections.Generic.Tree{T}+BranchCollection.GetEnumerator():System.Collections.IEnumerator{T}<Loom.Collections.Generic.Tree{T}<T>>")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Loom.Collections.Generic.Tree{T}+BranchCollection")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.ThreadStart")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.TimerCallback")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.WaitCallback")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Scope = "member", Target = "Loom.FormattableObject.ToString(System.Object,System.String,System.IFormatProvider):System.String")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Loom.Collections.DelimitedArray`1.Empty")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Loom.Net.Servers.ProtocolEventArgs`2.Empty")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.ThreadStart")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.TimerCallback")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Scope = "member", Target = "Loom.Threading.DelegateAdapter.op_Implicit(Loom.Threading.DelegateAdapter):System.Threading.WaitCallback")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:ValidateArgumentsOfPublicMethods", Scope = "member", Target = "Loom.Cryptography.HashProvider.Compare(System.String,System.String,System.Int32):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Loom.Collections.CircularQueue`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Collections.DelimitedArray`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Collections.CollectionList`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Collections.CircularQueue`1")]
[assembly: SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Loom.Collections.DataValueCollection`1.ValidateKey(T):System.Void")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Loom.Dynamic.DynamicType`1.CreatePropertyGetter(System.String):Loom.Dynamic.PropertyGetter`2<TObjectType,TPropertyType>")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Loom.Threading.ProcessQueue`1.System.Collections.ICollection.IsSynchronized")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Loom.Threading.ProcessQueue`1.System.Collections.ICollection.SyncRoot")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Loom.Threading.MultiThreadedProcessQueue`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Loom.Threading.ProcessQueue`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Threading.ProcessQueue`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Threading.MultiThreadedProcessQueue`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Collections.ISet`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Collections.Set`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Loom.Collections.DictionarySet`1")]
[assembly: SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "Loom.Collections.DelimitedArray`1.Empty")]
[assembly: SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "Loom.Net.Servers.ProtocolEventArgs`2.Empty")]
[assembly: SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "Loom.Net.Servers.ServerBinding.Default")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Loom.IO.Compression.Zip.Deflater.#BEST_SPEED")]