//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loom.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function cycleState(control) {
        ///    if (control.value == &apos;Hidden&apos;) {
        ///        control.style.backgroundColor = &apos;white&apos;;
        ///        control.style.borderColor = &apos;gray&apos;;
        ///        control.value = &apos;Optional&apos;;
        ///    }
        ///    else if (control.value == &apos;Required&apos;) {
        ///        control.style.backgroundColor = &apos;#E0E0E0&apos;;
        ///        control.style.borderColor = &apos;gray&apos;;
        ///        control.value = &apos;Hidden&apos;;
        ///    }
        ///    else {
        ///        control.style.backgroundColor = &apos;yellow&apos;;
        ///        control.style.borderColor = &apos;gray&apos;;
        ///        con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DragDropSnap {
            get {
                return ResourceManager.GetString("DragDropSnap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap IconRelationalDropDownList {
            get {
                object obj = ResourceManager.GetObject("IconRelationalDropDownList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRelationalListBox {
            get {
                object obj = ResourceManager.GetObject("IconRelationalListBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconRolloverImageButton {
            get {
                object obj = ResourceManager.GetObject("IconRolloverImageButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         DevInterop_PreloadSwapImages( DevInterop_Images ); .
        /// </summary>
        internal static string SwapImagePreloadScript {
            get {
                return ResourceManager.GetString("SwapImagePreloadScript", resourceCulture);
            }
        }
    }
}
